
FROM ruby:2.6.6



RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

ENV RAILS_ROOT /my_app


RUN mkdir -p $RAILS_ROOT

WORKDIR $RAILS_ROOT


COPY Gemfile Gemfile

COPY Gemfile.lock Gemfile.lock


RUN bundle install --jobs 20 --retry 5 --without production


COPY . .

RUN mkdir -p tmp/sockets
